# Generated by Django 6.0 on 2025-12-15 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: PE 90/2025', max_length=100, verbose_name='Identificador / Nº Edital')),
                ('orgao', models.CharField(help_text='Ex: Prefeitura de Ponta Grossa', max_length=200, verbose_name='Órgão / Cliente')),
                ('objeto', models.TextField(help_text='O que está sendo comprado?', verbose_name='Objeto da Licitação')),
                ('modalidade', models.CharField(choices=[('pregao_eletronico', 'Pregão Eletrônico'), ('pregao_presencial', 'Pregão Presencial'), ('concorrencia', 'Concorrência'), ('dispensa', 'Dispensa de Licitação'), ('cotacao', 'Cotação Eletrônica')], default='pregao_eletronico', max_length=30)),
                ('portal', models.CharField(blank=True, help_text='Ex: Comprasnet, Licitações-e', max_length=100, null=True, verbose_name='Portal')),
                ('data_abertura', models.DateTimeField(verbose_name='Data da Disputa')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado (R$)')),
                ('status', models.CharField(choices=[('novo', 'Novo Edital'), ('analise', 'Em Análise'), ('documentacao', 'Separando Documentos'), ('participando', 'Aguardando Disputa'), ('ganhamos', 'Ganhamos! 🏆'), ('perdemos', 'Perdemos'), ('suspenso', 'Suspenso/Cancelado')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Interno')),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
