# Generated by Django 6.0 on 2025-12-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='editais/', verbose_name='Edital / Arquivo'),
        ),
    ]
