# Generated by Django 6.0 on 2025-12-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0002_licitacao_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/', verbose_name='Arquivo Anexo')),
                ('descricao', models.CharField(help_text='Ex: Planilha de Custos, Projeto Básico', max_length=100, verbose_name='Nome do Arquivo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='licitacoes.licitacao')),
            ],
        ),
    ]
