# Generated by Django 6.0 on 2025-12-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0003_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Órgão / Cliente')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Setor')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço / Cidade')),
                ('portal_padrao', models.CharField(blank=True, help_text='Ex: Comprasnet', max_length=100, null=True, verbose_name='Portal Utilizado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente / Órgão',
                'verbose_name_plural': 'Clientes / Órgãos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='licitacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitacoes.cliente', verbose_name='Órgão (Cadastro)'),
        ),
    ]
