# Generated by Django 6.0 on 2025-12-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0004_cliente_licitacao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Anexo'),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='origem',
            field=models.CharField(default='MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='uasg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='url_origem',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Edital'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/', verbose_name='Arquivo Anexo'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='descricao',
            field=models.CharField(help_text='Ex: Planilha de Custos, Projeto Básico', max_length=255, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Disputa'),
        ),
        migrations.CreateModel(
            name='ItemLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Item')),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('objeto', models.TextField(verbose_name='Descrição do Item')),
                ('quantidade', models.CharField(max_length=50)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='licitacoes.licitacao')),
            ],
            options={
                'verbose_name': 'Item da Licitação',
                'verbose_name_plural': 'Itens da Licitação',
                'ordering': ['codigo'],
            },
        ),
    ]
